on:
  push:
    branches:
      - master

name: Deploy to Amazon S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: create zip
      run: |
        rm -rf templates/zips
        ./pack_templates.sh

    - name: Deploy zip to amazon S3
      run: |
        mkdir -p $HOME/.aws/
        echo -e "[default]\naws_access_key_id = $aws_access_key_id\naws_secret_access_key = $aws_secret_access_key\nregion=$aws-region\noutput=json" > $HOME/.aws/config
        aws s3 rm s3://templates.gauge.org --recursive
        cd templates/zips
        aws s3 sync . s3://templates.gauge.org --cache-control max-age=604800,s-maxage=1800
        aws s3 website s3://templates.gauge.org/ --index-document index.json